DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS jobs;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  jobName TEXT UNIQUE NOT NULL
);